package io.github.x1f4r.mmocraft.services;

import io.github.x1f4r.mmocraft.MMOCraft;
import io.github.x1f4r.mmocraft.core.MMOCore;
import io.github.x1f4r.mmocraft.core.Service;
import org.bukkit.NamespacedKey;
import org.bukkit.persistence.PersistentDataContainer;
import org.bukkit.persistence.PersistentDataType;

import java.util.Objects;

public class NBTService implements Service {
    private final MMOCraft plugin;
    private LoggingService logging; // For logging initialization

    // --- Player Base Stat Keys (PDC on Player object) ---
    // These are public static so other services can easily access them.
    // They are initialized in the initialize() method.
    public static NamespacedKey PLAYER_BASE_STRENGTH;
    public static NamespacedKey PLAYER_BASE_DEFENSE;
    public static NamespacedKey PLAYER_BASE_CRIT_CHANCE;
    public static NamespacedKey PLAYER_BASE_CRIT_DAMAGE;
    public static NamespacedKey PLAYER_BASE_MAX_HEALTH;
    public static NamespacedKey PLAYER_BASE_MAX_MANA;
    public static NamespacedKey PLAYER_BASE_SPEED_PERCENT; // Changed from PLAYER_BASE_SPEED for clarity
    public static NamespacedKey PLAYER_BASE_MINING_SPEED;
    public static NamespacedKey PLAYER_BASE_FORAGING_SPEED;
    public static NamespacedKey PLAYER_BASE_FISHING_SPEED;
    public static NamespacedKey PLAYER_BASE_SHOOTING_SPEED;

    // --- Item Stat Keys (PDC on ItemStack) ---
    public static NamespacedKey ITEM_ID_KEY; // The unique ID of the custom item template
    public static NamespacedKey ITEM_STAT_STRENGTH;
    public static NamespacedKey ITEM_STAT_DEFENSE;
    public static NamespacedKey ITEM_STAT_CRIT_CHANCE;
    public static NamespacedKey ITEM_STAT_CRIT_DAMAGE;
    public static NamespacedKey ITEM_STAT_MAX_HEALTH_BONUS;
    public static NamespacedKey ITEM_STAT_MAX_MANA_BONUS;
    public static NamespacedKey ITEM_STAT_SPEED_BONUS_PERCENT; // Bonus speed percentage
    public static NamespacedKey ITEM_STAT_MINING_SPEED_BONUS;
    public static NamespacedKey ITEM_STAT_FORAGING_SPEED_BONUS;
    public static NamespacedKey ITEM_STAT_FISHING_SPEED_BONUS;
    public static NamespacedKey ITEM_STAT_SHOOTING_SPEED_BONUS;

    // --- Keys for Part 3 (Combat & Visuals) ---
    public static NamespacedKey TRUE_DAMAGE_FLAG_KEY; // Byte: 1 for true, 0 for false (on Item or Projectile)
    public static NamespacedKey PROJECTILE_DAMAGE_MULTIPLIER; // Integer (on Projectile)
    public static NamespacedKey HEALTH_BAR_TAG_KEY; // Byte: 1 (on ArmorStand)
    public static NamespacedKey DAMAGE_INDICATOR_TAG_KEY; // Byte: 1 (on ArmorStand)

    // --- Keys for Part 4 (Tools & Compactors) ---
    public static NamespacedKey TOOL_ABILITY_ID; // String (on ItemStack)
    public static NamespacedKey TOOL_ABILITY_COOLDOWN_TICKS; // Integer (on ItemStack)
    public static NamespacedKey COMPACTOR_UTILITY_ID_KEY; // String (on ItemStack, e.g., "personal_compactor_t1")
    public static NamespacedKey COMPACTOR_SLOT_COUNT_KEY; // Integer (on ItemStack)
    // Dynamic compactor filter keys are generated by getCompactorFilterKey(int)

    // --- Keys for Part 5 (Abilities) ---
    public static NamespacedKey ABILITY_ID_KEY; // String (on ItemStack, links to ItemAbility.getAbilityId())
    public static NamespacedKey ABILITY_MANA_COST_OVERRIDE_KEY; // Integer (on ItemStack)
    public static NamespacedKey ABILITY_COOLDOWN_TICKS_OVERRIDE_KEY; // Integer (on ItemStack)
    // Generic ability parameter keys (example string constants for dynamic key creation)
    public static final String ABILITY_DAMAGE_PARAM_SUFFIX = "_ability_damage";
    public static final String ABILITY_DURATION_PARAM_SUFFIX = "_ability_duration";
    public static final String ABILITY_AMPLIFIER_PARAM_SUFFIX = "_ability_amplifier";
    public static final String ABILITY_RANGE_PARAM_SUFFIX = "_ability_range";
    // Projectile Data
    public static NamespacedKey PROJECTILE_IS_ABILITY_BOLT_FLAG; // Byte: 1
    public static NamespacedKey PROJECTILE_SOURCE_ABILITY_ID_KEY; // String
    public static NamespacedKey PROJECTILE_CUSTOM_DAMAGE; // Integer or Double
    public static NamespacedKey PROJECTILE_CUSTOM_EFFECT_TYPE; // String (e.g., "SLOW")
    public static NamespacedKey PROJECTILE_CUSTOM_EFFECT_DURATION; // Integer (ticks)
    public static NamespacedKey PROJECTILE_CUSTOM_EFFECT_AMPLIFIER; // Integer
    public static NamespacedKey PROJECTILE_CUSTOM_AOE_FLAG; // Byte: 1
    public static NamespacedKey PROJECTILE_CUSTOM_AOE_RADIUS_KEY; // Double
    public static NamespacedKey PROJECTILE_CUSTOM_AOE_DAMAGE_KEY; // Integer or Double
    public static final String ABILITY_RANGE_PARAM_KEY_STRING = "ability_range"; // e.g., for DragonFury range
    public static final String ABILITY_AOE_RADIUS_PARAM_KEY_STRING = "aoe_radius"; // For projectile AOE
    public static final String ABILITY_AOE_DAMAGE_PARAM_KEY_STRING = "aoe_damage"; // For projectile AOE damage
    public static final String ABILITY_IS_AOE_FLAG_PARAM_KEY_STRING = "is_aoe_on_hit"; // Boolean for projectile
    public static final String ABILITY_STRENGTH_SCALING_PARAM_KEY_STRING = "strength_scaling"; // e.g. for DragonFury
    public static final String ABILITY_BASE_SHOOT_COOLDOWN_PARAM_KEY_STRING = "base_shoot_cooldown_ticks"; // For InstantShotBow
    public static final String ABILITY_VELOCITY_MULTIPLIER_PARAM_KEY_STRING = "instant_shot_velocity_mult"; // For InstantShotBow
    // --- Keys for Part 6 (Custom Mobs) ---
    public static NamespacedKey CUSTOM_MOB_TYPE_ID_KEY; // String (on LivingEntity)


    public NBTService(MMOCraft plugin) {
        this.plugin = Objects.requireNonNull(plugin, "Plugin instance cannot be null for NBTService");
    }

    @Override
    public void initialize(MMOCore core) {
        this.logging = core.getService(LoggingService.class);

        // Player Base Stats
        PLAYER_BASE_STRENGTH = createKey("player_base_strength");
        PLAYER_BASE_DEFENSE = createKey("player_base_defense");
        // ... (initialize all other PLAYER_BASE_* keys)
        PLAYER_BASE_CRIT_CHANCE = createKey("player_base_crit_chance");
        PLAYER_BASE_CRIT_DAMAGE = createKey("player_base_crit_damage");
        PLAYER_BASE_MAX_HEALTH = createKey("player_base_max_health");
        PLAYER_BASE_MAX_MANA = createKey("player_base_max_mana");
        PLAYER_BASE_SPEED_PERCENT = createKey("player_base_speed_percent");
        PLAYER_BASE_MINING_SPEED = createKey("player_base_mining_speed");
        PLAYER_BASE_FORAGING_SPEED = createKey("player_base_foraging_speed");
        PLAYER_BASE_FISHING_SPEED = createKey("player_base_fishing_speed");
        PLAYER_BASE_SHOOTING_SPEED = createKey("player_base_shooting_speed");

        // Item Stats
        ITEM_ID_KEY = createKey("item_id");
        ITEM_STAT_STRENGTH = createKey("item_stat_strength");
        // ... (initialize all other ITEM_STAT_* keys) ...
        ITEM_STAT_DEFENSE = createKey("item_stat_defense");
        ITEM_STAT_CRIT_CHANCE = createKey("item_stat_crit_chance");
        ITEM_STAT_CRIT_DAMAGE = createKey("item_stat_crit_damage");
        ITEM_STAT_MAX_HEALTH_BONUS = createKey("item_stat_max_health_bonus");
        ITEM_STAT_MAX_MANA_BONUS = createKey("item_stat_max_mana_bonus");
        ITEM_STAT_SPEED_BONUS_PERCENT = createKey("item_stat_speed_bonus_percent");
        ITEM_STAT_MINING_SPEED_BONUS = createKey("item_stat_mining_speed_bonus");
        ITEM_STAT_FORAGING_SPEED_BONUS = createKey("item_stat_foraging_speed_bonus");
        ITEM_STAT_FISHING_SPEED_BONUS = createKey("item_stat_fishing_speed_bonus");
        ITEM_STAT_SHOOTING_SPEED_BONUS = createKey("item_stat_shooting_speed_bonus");

        // Part 3 Keys
        TRUE_DAMAGE_FLAG_KEY = createKey("true_damage_flag");
        PROJECTILE_DAMAGE_MULTIPLIER = createKey("projectile_damage_multiplier"); // Note: Used by ToolProf as well
        HEALTH_BAR_TAG_KEY = createKey("mmoc_health_bar_as"); // Already used in VisualFeedbackService
        DAMAGE_INDICATOR_TAG_KEY = createKey("mmoc_damage_indicator_as"); // Already used

        // Part 4 Keys
        TOOL_ABILITY_ID = createKey("tool_ability_id");
        TOOL_ABILITY_COOLDOWN_TICKS = createKey("tool_ability_cooldown");
        COMPACTOR_UTILITY_ID_KEY = createKey("compactor_id");
        COMPACTOR_SLOT_COUNT_KEY = createKey("compactor_slot_count");

        // Part 5 Keys
        ABILITY_ID_KEY = createKey("ability_id");
        ABILITY_MANA_COST_OVERRIDE_KEY = createKey("ability_mana_override");
        ABILITY_COOLDOWN_TICKS_OVERRIDE_KEY = createKey("ability_cooldown_override");
        PROJECTILE_IS_ABILITY_BOLT_FLAG = createKey("proj_is_ability_bolt");
        PROJECTILE_SOURCE_ABILITY_ID_KEY = createKey("proj_source_ability_id");
        PROJECTILE_CUSTOM_DAMAGE = createKey("proj_custom_damage");
        PROJECTILE_CUSTOM_EFFECT_TYPE = createKey("proj_custom_effect_type");
        PROJECTILE_CUSTOM_EFFECT_DURATION = createKey("proj_custom_effect_duration");
        PROJECTILE_CUSTOM_EFFECT_AMPLIFIER = createKey("proj_custom_effect_amplifier");
        PROJECTILE_CUSTOM_AOE_FLAG = createKey("proj_custom_aoe_flag");
        PROJECTILE_CUSTOM_AOE_RADIUS_KEY = createKey("proj_custom_aoe_radius");
        PROJECTILE_CUSTOM_AOE_DAMAGE_KEY = createKey("proj_custom_aoe_damage");

        // Part 6 Keys
        CUSTOM_MOB_TYPE_ID_KEY = createKey("custom_mob_type_id");

        logging.info(getServiceName() + " initialized with all predefined NamespacedKeys.");
    }

    @Override
    public void shutdown() {
        // Static fields, no specific shutdown needed unless dynamically managing keys (not the case here)
    }

    /**
     * Helper method to create NamespacedKey instances with the plugin's namespace.
     * @param key The string key.
     * @return A new NamespacedKey.
     */
    private NamespacedKey createKey(String key) {
        return new NamespacedKey(plugin, key.toLowerCase().replace(" ", "_"));
    }

    /**
     * Generates a NamespacedKey for a specific compactor filter slot.
     * @param slotIndex The 0-based index of the filter slot.
     * @return The NamespacedKey for that filter slot.
     */
    public static NamespacedKey getCompactorFilterKey(int slotIndex) {
        // Ensure plugin instance is available for key creation if called before NBTService init fully
        // (though static methods accessing instance fields before init is tricky).
        // Better to pass plugin instance or ensure this is only called after init.
        // For now, assuming NBTService is initialized and `plugin` field is set.
        return new NamespacedKey(MMOCraft.getInstance(), "compactor_filter_" + slotIndex);
    }

    /**
     * Creates a NamespacedKey for a generic ability parameter.
     * @param paramName e.g., "damage", "range" (will be prefixed with "ability_param_")
     * @return The NamespacedKey.
     */
    public static NamespacedKey getAbilityParameterKey(String paramName) {
        return new NamespacedKey(MMOCraft.getInstance(), "ability_param_" + paramName.toLowerCase().replace(" ", "_"));
    }


    // --- Generic PDC Helper Methods (Static for convenience) ---
    public static <T, Z> void set(PersistentDataContainer pdc, NamespacedKey key, PersistentDataType<T, Z> type, Z value) {
        Objects.requireNonNull(pdc, "PersistentDataContainer cannot be null.");
        Objects.requireNonNull(key, "NamespacedKey cannot be null.");
        Objects.requireNonNull(type, "PersistentDataType cannot be null.");
        if (value == null) {
            pdc.remove(key);
        } else {
            pdc.set(key, type, value);
        }
    }

    public static <T, Z> Z get(PersistentDataContainer pdc, NamespacedKey key, PersistentDataType<T, Z> type, Z defaultValue) {
        Objects.requireNonNull(pdc, "PersistentDataContainer cannot be null.");
        Objects.requireNonNull(key, "NamespacedKey cannot be null.");
        Objects.requireNonNull(type, "PersistentDataType cannot be null.");
        return pdc.getOrDefault(key, type, defaultValue);
    }

    public static boolean has(PersistentDataContainer pdc, NamespacedKey key, PersistentDataType<?, ?> type) {
        Objects.requireNonNull(pdc, "PersistentDataContainer cannot be null.");
        Objects.requireNonNull(key, "NamespacedKey cannot be null.");
        Objects.requireNonNull(type, "PersistentDataType cannot be null.");
        return pdc.has(key, type);
    }
}