# ------------------------------------------------------------
# Core loot table definitions
# ------------------------------------------------------------
# Each entry under "tables" defines a loot table keyed by its
# identifier. The entries list mirrors the Java LootTableEntry
# constructor parameters.
#
# "mob-assignments" optionally binds a Bukkit EntityType to one of
# the table identifiers declared above.
# ------------------------------------------------------------

tables:
  zombie_common_drops:
    entries:
      - type: CUSTOM
        id: simple_sword
        chance: 0.05
        min: 1
        max: 1
  stone_node_loot:
    entries:
      - type: VANILLA
        id: COBBLESTONE
        chance: 1.0
        min: 1
        max: 1
  iron_ore_node_loot:
    entries:
      - type: VANILLA
        id: RAW_IRON
        chance: 1.0
        min: 1
        max: 1
  warrior_common_loot:
    entries:
      - type: CUSTOM
        id: simple_sword
        chance: 0.25
        min: 1
        max: 1

mob-assignments:
  ZOMBIE: zombie_common_drops
