# ------------------------------------------------------------
# Hypixel-inspired player stat scaling controls
# ------------------------------------------------------------
defaults:
  base-investment: 0.0
  overrides: {}

scaling:
  health:
    base: 100.0
    per-point: 1.0
    per-level: 5.0
    min: 1.0
  defense:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    diminishing:
      threshold: 1000.0
      multiplier: 0.5
  true_defense:
    base: 0.0
    per-point: 1.0
    per-level: 0.25
  strength:
    base: 0.0
    per-point: 1.0
    per-level: 0.75
  critical_chance:
    base: 30.0
    per-point: 0.5
    per-level: 0.25
    min: 0.0
    max: 100.0
  critical_damage:
    base: 50.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  intelligence:
    base: 100.0
    per-point: 1.0
    per-level: 3.0
    min: 0.0
  mana_regen:
    base: 5.0
    per-point: 0.25
    per-level: 0.1
    min: 0.0
  ability_power:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  attack_speed:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
    max: 100.0
  ferocity:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
  evasion:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
    max: 60.0
  speed:
    base: 100.0
    per-point: 0.25
    per-level: 0.15
    min: 0.0
    max: 400.0
  magic_find:
    base: 0.0
    per-point: 0.25
    per-level: 0.05
    min: 0.0
  pet_luck:
    base: 0.0
    per-point: 0.1
    per-level: 0.05
    min: 0.0
  mining_speed:
    base: 0.0
    per-point: 2.0
    per-level: 1.0
    min: 0.0
  mining_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  farming_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  foraging_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  fishing_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0

combat:
  defense-reduction-base: 100.0
  true-defense-reduction-base: 100.0
  max-damage-reduction: 0.9
  max-evasion-chance: 0.6

runtime:
  movement:
    base-walk-speed: 0.2
    max-walk-speed: 0.6
    min-walk-speed: 0.05
    speed-baseline: 100.0
  combat:
    base-attack-speed: 4.0
    attack-speed-per-point: 0.02
    max-attack-speed: 8.0
    strength-physical-scaling: 0.5
    intelligence-magical-scaling: 0.7
    ability-power-percent-per-point: 1.0
    ferocity-per-extra-hit: 100.0
    ferocity-max-extra-hits: 4
    mob-defense-reduction-factor: 0.04
  ability:
    cooldown-reduction-per-attack-speed-point: 0.002
    cooldown-reduction-per-intelligence-point: 0.0
    minimum-cooldown-seconds: 0.2
    mana-cost-reduction-per-intelligence-point: 0.001
    mana-cost-reduction-per-ability-power-point: 0.001
    minimum-mana-cost-multiplier: 0.2
    minimum-mana-cost: 1.0
  gathering:
    base-gather-delay-seconds: 1.0
    minimum-gather-delay-seconds: 0.25
    mining-speed-delay-divisor: 100.0
    mining-speed-haste-per-tier: 80.0
    mining-speed-max-haste-tier: 4
    fortune-per-point:
      mining_fortune: 0.002
      farming_fortune: 0.002
      foraging_fortune: 0.002
      fishing_fortune: 0.0015
  mobs:
    health-per-level-percent: 0.05
    damage-per-level-percent: 0.03
    defense-per-level: 0.5
    max-health-multiplier: 5.0
    max-damage-multiplier: 5.0
    max-defense-bonus: 200.0

