# ------------------------------------------------------------
# Hypixel-inspired player stat scaling controls
# ------------------------------------------------------------
defaults:
  base-investment: 0.0
  overrides: {}

scaling:
  health:
    base: 100.0
    per-point: 1.0
    per-level: 5.0
    min: 1.0
  defense:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    diminishing:
      threshold: 1000.0
      multiplier: 0.5
  true_defense:
    base: 0.0
    per-point: 1.0
    per-level: 0.25
  strength:
    base: 0.0
    per-point: 1.0
    per-level: 0.75
  critical_chance:
    base: 30.0
    per-point: 0.5
    per-level: 0.25
    min: 0.0
    max: 100.0
  critical_damage:
    base: 50.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  intelligence:
    base: 100.0
    per-point: 1.0
    per-level: 3.0
    min: 0.0
  mana_regen:
    base: 5.0
    per-point: 0.25
    per-level: 0.1
    min: 0.0
  ability_power:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  attack_speed:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
    max: 100.0
  ferocity:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
  evasion:
    base: 0.0
    per-point: 0.5
    per-level: 0.2
    min: 0.0
    max: 60.0
  speed:
    base: 100.0
    per-point: 0.25
    per-level: 0.15
    min: 0.0
    max: 400.0
  magic_find:
    base: 0.0
    per-point: 0.25
    per-level: 0.05
    min: 0.0
  pet_luck:
    base: 0.0
    per-point: 0.1
    per-level: 0.05
    min: 0.0
  mining_speed:
    base: 0.0
    per-point: 2.0
    per-level: 1.0
    min: 0.0
  mining_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  farming_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  foraging_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0
  fishing_fortune:
    base: 0.0
    per-point: 1.0
    per-level: 0.5
    min: 0.0

combat:
  defense-reduction-base: 100.0
  true-defense-reduction-base: 100.0
  max-damage-reduction: 0.9
  max-evasion-chance: 0.6

